// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';
import 'schema_v10000.dart' as v10000;
import 'schema_v10083.dart' as v10083;
import 'schema_v10084.dart' as v10084;
import 'schema_v10085.dart' as v10085;
import 'schema_v10086.dart' as v10086;
import 'schema_v10087.dart' as v10087;
import 'schema_v10091.dart' as v10091;
import 'schema_v10092.dart' as v10092;
import 'schema_v10093.dart' as v10093;
import 'schema_v10095.dart' as v10095;
import 'schema_v10096.dart' as v10096;
import 'schema_v10097.dart' as v10097;
import 'schema_v10098.dart' as v10098;
import 'schema_v10099.dart' as v10099;
import 'schema_v10101.dart' as v10101;
import 'schema_v10102.dart' as v10102;
import 'schema_v10103.dart' as v10103;
import 'schema_v10104.dart' as v10104;
import 'schema_v10105.dart' as v10105;
import 'schema_v10106.dart' as v10106;
import 'schema_v10107.dart' as v10107;
import 'schema_v10108.dart' as v10108;
import 'schema_v10109.dart' as v10109;
import 'schema_v10110.dart' as v10110;
import 'schema_v10111.dart' as v10111;
import 'schema_v10112.dart' as v10112;
import 'schema_v10113.dart' as v10113;
import 'schema_v10114.dart' as v10114;
import 'schema_v10115.dart' as v10115;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 10000:
        return v10000.DatabaseAtV10000(db);
      case 10083:
        return v10083.DatabaseAtV10083(db);
      case 10084:
        return v10084.DatabaseAtV10084(db);
      case 10085:
        return v10085.DatabaseAtV10085(db);
      case 10086:
        return v10086.DatabaseAtV10086(db);
      case 10087:
        return v10087.DatabaseAtV10087(db);
      case 10091:
        return v10091.DatabaseAtV10091(db);
      case 10092:
        return v10092.DatabaseAtV10092(db);
      case 10093:
        return v10093.DatabaseAtV10093(db);
      case 10095:
        return v10095.DatabaseAtV10095(db);
      case 10096:
        return v10096.DatabaseAtV10096(db);
      case 10097:
        return v10097.DatabaseAtV10097(db);
      case 10098:
        return v10098.DatabaseAtV10098(db);
      case 10099:
        return v10099.DatabaseAtV10099(db);
      case 10101:
        return v10101.DatabaseAtV10101(db);
      case 10102:
        return v10102.DatabaseAtV10102(db);
      case 10103:
        return v10103.DatabaseAtV10103(db);
      case 10104:
        return v10104.DatabaseAtV10104(db);
      case 10105:
        return v10105.DatabaseAtV10105(db);
      case 10106:
        return v10106.DatabaseAtV10106(db);
      case 10107:
        return v10107.DatabaseAtV10107(db);
      case 10108:
        return v10108.DatabaseAtV10108(db);
      case 10109:
        return v10109.DatabaseAtV10109(db);
      case 10110:
        return v10110.DatabaseAtV10110(db);
      case 10111:
        return v10111.DatabaseAtV10111(db);
      case 10112:
        return v10112.DatabaseAtV10112(db);
      case 10113:
        return v10113.DatabaseAtV10113(db);
      case 10114:
        return v10114.DatabaseAtV10114(db);
      case 10115:
        return v10115.DatabaseAtV10115(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [
    10000,
    10083,
    10084,
    10085,
    10086,
    10087,
    10091,
    10092,
    10093,
    10095,
    10096,
    10097,
    10098,
    10099,
    10101,
    10102,
    10103,
    10104,
    10105,
    10106,
    10107,
    10108,
    10109,
    10110,
    10111,
    10112,
    10113,
    10114,
    10115,
  ];
}
