// Mocks generated by Mockito from annotations
// in tapix/test/features/products/presentation/widgets/bulk_product_row_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:decimal/decimal.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tapix/core/services/currency_service.dart' as _i2;
import 'package:tapix/core/services/inventory/inventory_adjustment_service.dart'
    as _i4;
import 'package:tapix/features/products/domain/entities/product_color_entity.dart'
    as _i9;
import 'package:tapix/features/products/domain/entities/product_variant_entity.dart'
    as _i7;
import 'package:tapix/features/products/domain/entities/size_entity.dart'
    as _i10;
import 'package:tapix/features/products/domain/repositories/product_color_repository.dart'
    as _i11;
import 'package:tapix/features/products/domain/repositories/product_variant_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCurrency_0 extends _i1.SmartFake implements _i2.Currency {
  _FakeCurrency_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVariantDeletionResult_1 extends _i1.SmartFake
    implements _i3.VariantDeletionResult {
  _FakeVariantDeletionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInventoryAdjustmentResult_2 extends _i1.SmartFake
    implements _i4.InventoryAdjustmentResult {
  _FakeInventoryAdjustmentResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrencyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyService extends _i1.Mock implements _i2.CurrencyService {
  MockCurrencyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Currency> get customCurrencies =>
      (super.noSuchMethod(
            Invocation.getter(#customCurrencies),
            returnValue: <_i2.Currency>[],
          )
          as List<_i2.Currency>);

  @override
  _i5.Stream<_i2.Currency> get currencyStream =>
      (super.noSuchMethod(
            Invocation.getter(#currencyStream),
            returnValue: _i5.Stream<_i2.Currency>.empty(),
          )
          as _i5.Stream<_i2.Currency>);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  String get currencySymbol =>
      (super.noSuchMethod(
            Invocation.getter(#currencySymbol),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currencySymbol),
            ),
          )
          as String);

  @override
  _i2.SymbolPosition get symbolPosition =>
      (super.noSuchMethod(
            Invocation.getter(#symbolPosition),
            returnValue: _i2.SymbolPosition.before,
          )
          as _i2.SymbolPosition);

  @override
  _i5.Future<void> addCustomCurrency(_i2.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomCurrency, [currency]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeCustomCurrency(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#removeCustomCurrency, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.Currency getCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrency, []),
            returnValue: _FakeCurrency_0(
              this,
              Invocation.method(#getCurrency, []),
            ),
          )
          as _i2.Currency);

  @override
  _i5.Future<void> setCurrency(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrency, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String format(int? cents, {bool? showSymbol = true}) =>
      (super.noSuchMethod(
            Invocation.method(#format, [cents], {#showSymbol: showSymbol}),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#format, [cents], {#showSymbol: showSymbol}),
            ),
          )
          as String);

  @override
  String formatForCode(
    int? minorUnits,
    String? currencyCode, {
    bool? showSymbol = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #formatForCode,
              [minorUnits, currencyCode],
              {#showSymbol: showSymbol},
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #formatForCode,
                [minorUnits, currencyCode],
                {#showSymbol: showSymbol},
              ),
            ),
          )
          as String);

  @override
  String formatCents(int? cents, {bool? showSymbol = true}) =>
      (super.noSuchMethod(
            Invocation.method(#formatCents, [cents], {#showSymbol: showSymbol}),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #formatCents,
                [cents],
                {#showSymbol: showSymbol},
              ),
            ),
          )
          as String);

  @override
  String centsToDecimalString(int? cents) =>
      (super.noSuchMethod(
            Invocation.method(#centsToDecimalString, [cents]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#centsToDecimalString, [cents]),
            ),
          )
          as String);

  @override
  String minorUnitsToDecimalStringForCode(
    int? minorUnits,
    String? currencyCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#minorUnitsToDecimalStringForCode, [
              minorUnits,
              currencyCode,
            ]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#minorUnitsToDecimalStringForCode, [
                minorUnits,
                currencyCode,
              ]),
            ),
          )
          as String);

  @override
  int decimalDigitsForCode(String? currencyCode) =>
      (super.noSuchMethod(
            Invocation.method(#decimalDigitsForCode, [currencyCode]),
            returnValue: 0,
          )
          as int);

  @override
  int decimalStringToCents(String? decimalString) =>
      (super.noSuchMethod(
            Invocation.method(#decimalStringToCents, [decimalString]),
            returnValue: 0,
          )
          as int);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProductVariantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductVariantRepository extends _i1.Mock
    implements _i3.ProductVariantRepository {
  MockProductVariantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i7.ProductVariant>> watchAllVariants() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllVariants, []),
            returnValue: _i5.Stream<List<_i7.ProductVariant>>.empty(),
          )
          as _i5.Stream<List<_i7.ProductVariant>>);

  @override
  _i5.Stream<List<_i7.ProductVariant>> watchVariantsByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantsByProduct, [productId]),
            returnValue: _i5.Stream<List<_i7.ProductVariant>>.empty(),
          )
          as _i5.Stream<List<_i7.ProductVariant>>);

  @override
  _i5.Future<List<_i7.ProductVariant>> getVariantsByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantsByProduct, [productId]),
            returnValue: _i5.Future<List<_i7.ProductVariant>>.value(
              <_i7.ProductVariant>[],
            ),
          )
          as _i5.Future<List<_i7.ProductVariant>>);

  @override
  _i5.Future<_i7.ProductVariant?> getVariantById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantById, [id]),
            returnValue: _i5.Future<_i7.ProductVariant?>.value(),
          )
          as _i5.Future<_i7.ProductVariant?>);

  @override
  _i5.Future<_i7.ProductVariant?> getVariantByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantByBarcode, [barcode]),
            returnValue: _i5.Future<_i7.ProductVariant?>.value(),
          )
          as _i5.Future<_i7.ProductVariant?>);

  @override
  _i5.Future<_i7.ProductVariant?> getVariantBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantBySku, [sku]),
            returnValue: _i5.Future<_i7.ProductVariant?>.value(),
          )
          as _i5.Future<_i7.ProductVariant?>);

  @override
  _i5.Future<_i7.ProductVariant?> getDefaultVariantByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultVariantByProduct, [productId]),
            returnValue: _i5.Future<_i7.ProductVariant?>.value(),
          )
          as _i5.Future<_i7.ProductVariant?>);

  @override
  _i5.Future<int> ensureDefaultVariantForProduct({
    required int? productId,
    required _i8.Decimal? costCents,
    required _i8.Decimal? priceCents,
    required int? stockQuantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ensureDefaultVariantForProduct, [], {
              #productId: productId,
              #costCents: costCents,
              #priceCents: priceCents,
              #stockQuantity: stockQuantity,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> createVariant({
    required int? productId,
    String? sku,
    String? barcode,
    int? colorId,
    int? sizeId,
    required _i8.Decimal? costCents,
    required _i8.Decimal? priceCents,
    _i8.Decimal? wholesalePriceCents,
    required int? stockQuantity,
    bool? isActive = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createVariant, [], {
              #productId: productId,
              #sku: sku,
              #barcode: barcode,
              #colorId: colorId,
              #sizeId: sizeId,
              #costCents: costCents,
              #priceCents: priceCents,
              #wholesalePriceCents: wholesalePriceCents,
              #stockQuantity: stockQuantity,
              #isActive: isActive,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateVariant(_i7.ProductVariant? variant) =>
      (super.noSuchMethod(
            Invocation.method(#updateVariant, [variant]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteVariant(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVariant, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countVariantReferences(int? variantId) =>
      (super.noSuchMethod(
            Invocation.method(#countVariantReferences, [variantId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.VariantDeletionResult> smartDeleteVariant(int? variantId) =>
      (super.noSuchMethod(
            Invocation.method(#smartDeleteVariant, [variantId]),
            returnValue: _i5.Future<_i3.VariantDeletionResult>.value(
              _FakeVariantDeletionResult_1(
                this,
                Invocation.method(#smartDeleteVariant, [variantId]),
              ),
            ),
          )
          as _i5.Future<_i3.VariantDeletionResult>);

  @override
  _i5.Future<_i3.VariantDeletionResult> writeOffAndDeleteVariant({
    required int? variantId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#writeOffAndDeleteVariant, [], {
              #variantId: variantId,
              #reason: reason,
            }),
            returnValue: _i5.Future<_i3.VariantDeletionResult>.value(
              _FakeVariantDeletionResult_1(
                this,
                Invocation.method(#writeOffAndDeleteVariant, [], {
                  #variantId: variantId,
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.VariantDeletionResult>);

  @override
  _i5.Future<int> countActiveDimensionalVariants(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#countActiveDimensionalVariants, [productId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countActiveDimensionalVariantsWithStock(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#countActiveDimensionalVariantsWithStock, [
              productId,
            ]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deactivateDimensionalVariants(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateDimensionalVariants, [productId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i4.InventoryAdjustmentResult> adjustStock({
    required int? variantId,
    required _i4.InventoryAdjustmentType? type,
    required int? quantityDelta,
    required String? reason,
    String? notes,
    required int? currencyId,
    int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #variantId: variantId,
              #type: type,
              #quantityDelta: quantityDelta,
              #reason: reason,
              #notes: notes,
              #currencyId: currencyId,
              #userId: userId,
            }),
            returnValue: _i5.Future<_i4.InventoryAdjustmentResult>.value(
              _FakeInventoryAdjustmentResult_2(
                this,
                Invocation.method(#adjustStock, [], {
                  #variantId: variantId,
                  #type: type,
                  #quantityDelta: quantityDelta,
                  #reason: reason,
                  #notes: notes,
                  #currencyId: currencyId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.InventoryAdjustmentResult>);

  @override
  _i5.Future<bool> isSkuTaken(String? sku, {int? excludeVariantId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isSkuTaken,
              [sku],
              {#excludeVariantId: excludeVariantId},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBarcodeTaken(String? barcode, {int? excludeVariantId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isBarcodeTaken,
              [barcode],
              {#excludeVariantId: excludeVariantId},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> variantExists({
    required int? productId,
    int? colorId,
    int? sizeId,
    int? excludeVariantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#variantExists, [], {
              #productId: productId,
              #colorId: colorId,
              #sizeId: sizeId,
              #excludeVariantId: excludeVariantId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<Map<int, ({int count, int totalStock})>> watchVariantSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantSummaries, []),
            returnValue:
                _i5.Stream<Map<int, ({int count, int totalStock})>>.empty(),
          )
          as _i5.Stream<Map<int, ({int count, int totalStock})>>);

  @override
  _i5.Stream<Map<int, ({String? colorHex, String? sizeName})>>
  watchVariantPreviews() =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantPreviews, []),
            returnValue:
                _i5.Stream<
                  Map<int, ({String? colorHex, String? sizeName})>
                >.empty(),
          )
          as _i5.Stream<Map<int, ({String? colorHex, String? sizeName})>>);

  @override
  _i5.Future<({int count, int totalStock})?> getVariantSummaryByProduct(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantSummaryByProduct, [productId]),
            returnValue: _i5.Future<({int count, int totalStock})?>.value(),
          )
          as _i5.Future<({int count, int totalStock})?>);

  @override
  _i5.Stream<List<_i9.ProductColor>> watchAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllColors, []),
            returnValue: _i5.Stream<List<_i9.ProductColor>>.empty(),
          )
          as _i5.Stream<List<_i9.ProductColor>>);

  @override
  _i5.Future<List<_i9.ProductColor>> getAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllColors, []),
            returnValue: _i5.Future<List<_i9.ProductColor>>.value(
              <_i9.ProductColor>[],
            ),
          )
          as _i5.Future<List<_i9.ProductColor>>);

  @override
  _i5.Future<int> createColor(String? name, String? hexCode) =>
      (super.noSuchMethod(
            Invocation.method(#createColor, [name, hexCode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateColor(_i9.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteColor(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteColor, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<List<_i10.Size>> watchAllSizes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSizes, []),
            returnValue: _i5.Stream<List<_i10.Size>>.empty(),
          )
          as _i5.Stream<List<_i10.Size>>);

  @override
  _i5.Future<List<_i10.Size>> getAllSizes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSizes, []),
            returnValue: _i5.Future<List<_i10.Size>>.value(<_i10.Size>[]),
          )
          as _i5.Future<List<_i10.Size>>);

  @override
  _i5.Future<int> createSize(
    String? name,
    int? sortOrder,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSize, [name, sortOrder, description]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateSize(_i10.Size? size) =>
      (super.noSuchMethod(
            Invocation.method(#updateSize, [size]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteSize(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSize, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [ProductColorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductColorRepository extends _i1.Mock
    implements _i11.ProductColorRepository {
  MockProductColorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i9.ProductColor>> watchAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllColors, []),
            returnValue: _i5.Stream<List<_i9.ProductColor>>.empty(),
          )
          as _i5.Stream<List<_i9.ProductColor>>);

  @override
  _i5.Stream<List<_i9.ProductColor>> watchColorsBySearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#watchColorsBySearch, [query]),
            returnValue: _i5.Stream<List<_i9.ProductColor>>.empty(),
          )
          as _i5.Stream<List<_i9.ProductColor>>);

  @override
  _i5.Future<List<_i9.ProductColor>> getAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllColors, []),
            returnValue: _i5.Future<List<_i9.ProductColor>>.value(
              <_i9.ProductColor>[],
            ),
          )
          as _i5.Future<List<_i9.ProductColor>>);

  @override
  _i5.Future<_i9.ProductColor?> getColorById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getColorById, [id]),
            returnValue: _i5.Future<_i9.ProductColor?>.value(),
          )
          as _i5.Future<_i9.ProductColor?>);

  @override
  _i5.Future<int> createColor(_i9.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#createColor, [color]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateColor(_i9.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteColor(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteColor, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> getProductCountByColor(int? colorId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductCountByColor, [colorId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> hasProducts(int? colorId) =>
      (super.noSuchMethod(
            Invocation.method(#hasProducts, [colorId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
