// Mocks generated by Mockito 5.4.6 from annotations
// in tapix/test/features/products/presentation/widgets/bulk_product_row_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:decimal/decimal.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:tapix/core/services/currency_service.dart' as _i2;
import 'package:tapix/features/products/domain/entities/product_color_entity.dart'
    as _i8;
import 'package:tapix/features/products/domain/entities/product_variant_entity.dart'
    as _i6;
import 'package:tapix/features/products/domain/entities/size_entity.dart'
    as _i9;
import 'package:tapix/features/products/domain/repositories/product_color_repository.dart'
    as _i10;
import 'package:tapix/features/products/domain/repositories/product_variant_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCurrency_0 extends _i1.SmartFake implements _i2.Currency {
  _FakeCurrency_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrencyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyService extends _i1.Mock implements _i2.CurrencyService {
  MockCurrencyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.Currency> get currencyStream =>
      (super.noSuchMethod(
            Invocation.getter(#currencyStream),
            returnValue: _i3.Stream<_i2.Currency>.empty(),
          )
          as _i3.Stream<_i2.Currency>);

  @override
  String get currencyCode =>
      (super.noSuchMethod(
            Invocation.getter(#currencyCode),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currencyCode),
            ),
          )
          as String);

  @override
  String get currencySymbol =>
      (super.noSuchMethod(
            Invocation.getter(#currencySymbol),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currencySymbol),
            ),
          )
          as String);

  @override
  _i2.SymbolPosition get symbolPosition =>
      (super.noSuchMethod(
            Invocation.getter(#symbolPosition),
            returnValue: _i2.SymbolPosition.before,
          )
          as _i2.SymbolPosition);

  @override
  _i2.Currency getCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrency, []),
            returnValue: _FakeCurrency_0(
              this,
              Invocation.method(#getCurrency, []),
            ),
          )
          as _i2.Currency);

  @override
  _i3.Future<void> setCurrency(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrency, [code]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String format(int? cents, {bool? showSymbol = true}) =>
      (super.noSuchMethod(
            Invocation.method(#format, [cents], {#showSymbol: showSymbol}),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#format, [cents], {#showSymbol: showSymbol}),
            ),
          )
          as String);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ProductVariantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductVariantRepository extends _i1.Mock
    implements _i5.ProductVariantRepository {
  MockProductVariantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.ProductVariant>> watchAllVariants() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllVariants, []),
            returnValue: _i3.Stream<List<_i6.ProductVariant>>.empty(),
          )
          as _i3.Stream<List<_i6.ProductVariant>>);

  @override
  _i3.Stream<List<_i6.ProductVariant>> watchVariantsByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantsByProduct, [productId]),
            returnValue: _i3.Stream<List<_i6.ProductVariant>>.empty(),
          )
          as _i3.Stream<List<_i6.ProductVariant>>);

  @override
  _i3.Future<List<_i6.ProductVariant>> getVariantsByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantsByProduct, [productId]),
            returnValue: _i3.Future<List<_i6.ProductVariant>>.value(
              <_i6.ProductVariant>[],
            ),
          )
          as _i3.Future<List<_i6.ProductVariant>>);

  @override
  _i3.Future<_i6.ProductVariant?> getVariantById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantById, [id]),
            returnValue: _i3.Future<_i6.ProductVariant?>.value(),
          )
          as _i3.Future<_i6.ProductVariant?>);

  @override
  _i3.Future<_i6.ProductVariant?> getVariantByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantByBarcode, [barcode]),
            returnValue: _i3.Future<_i6.ProductVariant?>.value(),
          )
          as _i3.Future<_i6.ProductVariant?>);

  @override
  _i3.Future<_i6.ProductVariant?> getVariantBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantBySku, [sku]),
            returnValue: _i3.Future<_i6.ProductVariant?>.value(),
          )
          as _i3.Future<_i6.ProductVariant?>);

  @override
  _i3.Future<_i6.ProductVariant?> getDefaultVariantByProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultVariantByProduct, [productId]),
            returnValue: _i3.Future<_i6.ProductVariant?>.value(),
          )
          as _i3.Future<_i6.ProductVariant?>);

  @override
  _i3.Future<int> ensureDefaultVariantForProduct({
    required int? productId,
    required _i7.Decimal? costCents,
    required _i7.Decimal? priceCents,
    required int? stockQuantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ensureDefaultVariantForProduct, [], {
              #productId: productId,
              #costCents: costCents,
              #priceCents: priceCents,
              #stockQuantity: stockQuantity,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> createVariant({
    required int? productId,
    String? sku,
    String? barcode,
    int? colorId,
    int? sizeId,
    required _i7.Decimal? costCents,
    required _i7.Decimal? priceCents,
    _i7.Decimal? wholesalePriceCents,
    required int? stockQuantity,
    bool? isActive = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createVariant, [], {
              #productId: productId,
              #sku: sku,
              #barcode: barcode,
              #colorId: colorId,
              #sizeId: sizeId,
              #costCents: costCents,
              #priceCents: priceCents,
              #wholesalePriceCents: wholesalePriceCents,
              #stockQuantity: stockQuantity,
              #isActive: isActive,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateVariant(_i6.ProductVariant? variant) =>
      (super.noSuchMethod(
            Invocation.method(#updateVariant, [variant]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteVariant(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVariant, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> isSkuTaken(String? sku, {int? excludeVariantId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isSkuTaken,
              [sku],
              {#excludeVariantId: excludeVariantId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isBarcodeTaken(String? barcode, {int? excludeVariantId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isBarcodeTaken,
              [barcode],
              {#excludeVariantId: excludeVariantId},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> variantExists({
    required int? productId,
    int? colorId,
    int? sizeId,
    int? excludeVariantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#variantExists, [], {
              #productId: productId,
              #colorId: colorId,
              #sizeId: sizeId,
              #excludeVariantId: excludeVariantId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<Map<int, ({int count, int totalStock})>> watchVariantSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantSummaries, []),
            returnValue:
                _i3.Stream<Map<int, ({int count, int totalStock})>>.empty(),
          )
          as _i3.Stream<Map<int, ({int count, int totalStock})>>);

  @override
  _i3.Stream<Map<int, ({String? colorHex, String? sizeName})>>
  watchVariantPreviews() =>
      (super.noSuchMethod(
            Invocation.method(#watchVariantPreviews, []),
            returnValue:
                _i3.Stream<
                  Map<int, ({String? colorHex, String? sizeName})>
                >.empty(),
          )
          as _i3.Stream<Map<int, ({String? colorHex, String? sizeName})>>);

  @override
  _i3.Future<({int count, int totalStock})?> getVariantSummaryByProduct(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVariantSummaryByProduct, [productId]),
            returnValue: _i3.Future<({int count, int totalStock})?>.value(),
          )
          as _i3.Future<({int count, int totalStock})?>);

  @override
  _i3.Stream<List<_i8.ProductColor>> watchAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllColors, []),
            returnValue: _i3.Stream<List<_i8.ProductColor>>.empty(),
          )
          as _i3.Stream<List<_i8.ProductColor>>);

  @override
  _i3.Future<List<_i8.ProductColor>> getAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllColors, []),
            returnValue: _i3.Future<List<_i8.ProductColor>>.value(
              <_i8.ProductColor>[],
            ),
          )
          as _i3.Future<List<_i8.ProductColor>>);

  @override
  _i3.Future<int> createColor(String? name, String? hexCode) =>
      (super.noSuchMethod(
            Invocation.method(#createColor, [name, hexCode]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateColor(_i8.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteColor(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteColor, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Stream<List<_i9.Size>> watchAllSizes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSizes, []),
            returnValue: _i3.Stream<List<_i9.Size>>.empty(),
          )
          as _i3.Stream<List<_i9.Size>>);

  @override
  _i3.Future<List<_i9.Size>> getAllSizes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSizes, []),
            returnValue: _i3.Future<List<_i9.Size>>.value(<_i9.Size>[]),
          )
          as _i3.Future<List<_i9.Size>>);

  @override
  _i3.Future<int> createSize(
    String? name,
    int? sortOrder,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSize, [name, sortOrder, description]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateSize(_i9.Size? size) =>
      (super.noSuchMethod(
            Invocation.method(#updateSize, [size]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteSize(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSize, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [ProductColorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductColorRepository extends _i1.Mock
    implements _i10.ProductColorRepository {
  MockProductColorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i8.ProductColor>> watchAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllColors, []),
            returnValue: _i3.Stream<List<_i8.ProductColor>>.empty(),
          )
          as _i3.Stream<List<_i8.ProductColor>>);

  @override
  _i3.Stream<List<_i8.ProductColor>> watchColorsBySearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#watchColorsBySearch, [query]),
            returnValue: _i3.Stream<List<_i8.ProductColor>>.empty(),
          )
          as _i3.Stream<List<_i8.ProductColor>>);

  @override
  _i3.Future<List<_i8.ProductColor>> getAllColors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllColors, []),
            returnValue: _i3.Future<List<_i8.ProductColor>>.value(
              <_i8.ProductColor>[],
            ),
          )
          as _i3.Future<List<_i8.ProductColor>>);

  @override
  _i3.Future<_i8.ProductColor?> getColorById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getColorById, [id]),
            returnValue: _i3.Future<_i8.ProductColor?>.value(),
          )
          as _i3.Future<_i8.ProductColor?>);

  @override
  _i3.Future<int> createColor(_i8.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#createColor, [color]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateColor(_i8.ProductColor? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteColor(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteColor, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getProductCountByColor(int? colorId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductCountByColor, [colorId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> hasProducts(int? colorId) =>
      (super.noSuchMethod(
            Invocation.method(#hasProducts, [colorId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
