import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import '../../../core/database/app_database.dart';
import '../../../core/services/business/warehouse_read_scope.dart';
import '../../../core/services/business/warehouse_transfer_preflight.dart';

enum TransferDraftAction { create, read, cancel, dispatch, receive, recall }

/// The application boundary must check the current session, role and Pro
/// access for both warehouses, and return the authenticated local user ID.
typedef AuthorizeTransferDraft =
    Future<int> Function(
      TransferDraftAction action,
      String sourceWarehouseId,
      String destinationWarehouseId,
    );

class WarehouseTransferDraft {
  WarehouseTransferDraft(
    this.header,
    List<WarehouseTransferLine> lines, {
    this.recall,
  }) : lines = List.unmodifiable(lines);
  final WarehouseTransfer header;
  final List<WarehouseTransferLine> lines;
  final WarehouseTransferRecall? recall;
}

/// Persists reviewed intent only. Drafts do not reserve stock or freeze dispatch
/// costs. Every future dispatch must obtain a new preview and post atomically.
class WarehouseTransferRepository {
  WarehouseTransferRepository(
    this.db, {
    required this.preflight,
    required this.authorize,
  });
  final AppDatabase db;
  final WarehouseTransferPreflight preflight;
  final AuthorizeTransferDraft authorize;
  static String _key(String input) {
    final key = input.trim().toLowerCase();
    if (!RegExp(
      r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
    ).hasMatch(key)) {
      throw ArgumentError(
        'A stable UUID operation key generated by the branch app is required',
      );
    }
    return key;
  }

  static String _hash(Object value) =>
      sha256.convert(utf8.encode(jsonEncode(value))).toString();
  Future<int> _actor(
    TransferDraftAction action,
    String source,
    String destination,
  ) async {
    final actor = await authorize(action, source, destination);
    final user =
        await (db.select(db.users)
              ..where((u) => u.id.equals(actor) & u.isActive.equals(1)))
            .getSingleOrNull();
    if (user == null) {
      throw StateError('Transfer requires an active authenticated user');
    }
    return actor;
  }

  Future<void> _binding(WarehouseTransfer header) async {
    final from = await WarehouseReadScope.resolve(
      db,
      warehouseId: header.sourceWarehouseId,
    );
    final to = await WarehouseReadScope.resolve(
      db,
      warehouseId: header.destinationWarehouseId,
    );
    for (final scope in [from, to]) {
      if (scope.organizationId != header.organizationId ||
          scope.branchId != header.branchId ||
          scope.databaseId != header.databaseId) {
        throw StateError(
          'Transfer does not belong to this database and branch',
        );
      }
    }
  }

  Future<WarehouseTransferDraft> _result(WarehouseTransfer header) async {
    if (!header.sealed) {
      throw StateError('Transfer draft is incomplete');
    }
    final lines =
        await (db.select(db.warehouseTransferLines)
              ..where((l) => l.transferId.equals(header.id))
              ..orderBy([(l) => OrderingTerm.asc(l.variantId)]))
            .get();
    if (lines.length != header.lineCount) {
      throw StateError('Transfer line count changed');
    }
    final recall = await (db.select(
      db.warehouseTransferRecalls,
    )..where((row) => row.transferId.equals(header.id))).getSingleOrNull();
    return WarehouseTransferDraft(header, lines, recall: recall);
  }

  Future<List<WarehouseTransferDraft>> list({
    Set<String>? statuses,
    int limit = 100,
  }) => db.transaction(() async {
    if (limit < 1 || limit > 500) throw ArgumentError.value(limit, 'limit');
    const validStatuses = {
      'draft',
      'in_transit',
      'partially_received',
      'completed',
      'cancelled',
    };
    final selected = statuses ?? validStatuses;
    if (selected.isEmpty || !validStatuses.containsAll(selected)) {
      throw ArgumentError.value(statuses, 'statuses');
    }
    final rows =
        await (db.select(db.warehouseTransfers)
              ..where((row) => row.status.isIn(selected))
              ..orderBy([(row) => OrderingTerm.desc(row.createdAt)])
              ..limit(limit))
            .get();
    final result = <WarehouseTransferDraft>[];
    for (final row in rows) {
      await _actor(
        TransferDraftAction.read,
        row.sourceWarehouseId,
        row.destinationWarehouseId,
      );
      await _binding(row);
      result.add(await _result(row));
    }
    return List.unmodifiable(result);
  });

  Future<WarehouseTransferDraft> get(String id) => db.transaction(() async {
    final header = await (db.select(
      db.warehouseTransfers,
    )..where((t) => t.id.equals(id))).getSingle();
    await _actor(
      TransferDraftAction.read,
      header.sourceWarehouseId,
      header.destinationWarehouseId,
    );
    await _binding(header);
    return _result(header);
  });
  Future<WarehouseTransferDraft> create({
    required String requestKey,
    required WarehouseTransferPreview preview,
    String notes = '',
  }) => db.transaction(() async {
    final key = _key(requestKey), normalizedNotes = notes.trim();
    if (normalizedNotes.length > 500) {
      throw ArgumentError('Transfer notes exceed 500 characters');
    }
    final source = preview.source, destination = preview.destination;
    final actor = await _actor(
      TransferDraftAction.create,
      source.warehouseId,
      destination.warehouseId,
    );
    await source.validate(db);
    await destination.validate(db);
    final lines = preview.lines.toList()
      ..sort((a, b) => a.variantId.compareTo(b.variantId));
    final hash = _hash({
      'version': 1,
      'organization': source.organizationId,
      'branch': source.branchId,
      'database': source.databaseId,
      'source': source.warehouseId,
      'destination': destination.warehouseId,
      'currency': preview.currencyId,
      'actor': actor,
      'notes': normalizedNotes,
      'lines': [
        for (final line in lines)
          [
            line.request.productId,
            line.variantId,
            line.request.quantity,
            line.quantityScale,
            line.measurementType,
          ],
      ],
    });
    final prior = await (db.select(
      db.warehouseTransfers,
    )..where((t) => t.requestKey.equals(key))).getSingleOrNull();
    if (prior != null) {
      await _binding(prior);
      if (prior.requestHash != hash) {
        throw StateError(
          'Request key already belongs to different transfer intent',
        );
      }
      // A retry after stock changes or cancellation returns the SAME document.
      return _result(prior);
    }
    await preflight.validateUnchanged(preview);
    final id = const Uuid().v4();
    await db
        .into(db.warehouseTransfers)
        .insert(
          WarehouseTransfersCompanion.insert(
            id: id,
            organizationId: source.organizationId,
            branchId: source.branchId,
            databaseId: source.databaseId,
            sourceWarehouseId: source.warehouseId,
            destinationWarehouseId: destination.warehouseId,
            currencyId: preview.currencyId,
            createdBy: actor,
            requestKey: key,
            requestHash: hash,
            notes: Value(normalizedNotes),
            lineCount: lines.length,
          ),
        );
    for (final line in lines) {
      await db
          .into(db.warehouseTransferLines)
          .insert(
            WarehouseTransferLinesCompanion.insert(
              id: const Uuid().v4(),
              transferId: id,
              productId: line.request.productId,
              variantId: line.variantId,
              quantity: line.request.quantity,
              quantityScale: line.quantityScale,
              measurementType: line.measurementType,
              previewValueCents: line.valueCents,
            ),
          );
    }
    await (db.update(db.warehouseTransfers)..where((t) => t.id.equals(id)))
        .write(const WarehouseTransfersCompanion(sealed: Value(true)));
    await db
        .into(db.warehouseTransferEvents)
        .insert(
          WarehouseTransferEventsCompanion.insert(
            id: const Uuid().v4(),
            transferId: id,
            kind: 'created',
            requestKey: key,
            requestHash: hash,
            actorId: actor,
          ),
        );
    return _result(
      await (db.select(
        db.warehouseTransfers,
      )..where((t) => t.id.equals(id))).getSingle(),
    );
  });
  Future<WarehouseTransferDraft> cancel({
    required String id,
    required String requestKey,
    required String reason,
  }) => db.transaction(() async {
    final key = _key(requestKey), text = reason.trim();
    if (text.isEmpty || text.length > 500) {
      throw ArgumentError(
        'Cancellation requires a reason of 1 to 500 characters',
      );
    }
    final header = await (db.select(
      db.warehouseTransfers,
    )..where((t) => t.id.equals(id))).getSingle();
    final actor = await _actor(
      TransferDraftAction.cancel,
      header.sourceWarehouseId,
      header.destinationWarehouseId,
    );
    await _binding(header);
    final hash = _hash({
      'version': 1,
      'kind': 'cancelled',
      'id': id,
      'actor': actor,
      'reason': text,
    });
    final prior = await (db.select(
      db.warehouseTransferEvents,
    )..where((e) => e.requestKey.equals(key))).getSingleOrNull();
    if (prior != null) {
      if (prior.transferId != id ||
          prior.kind != 'cancelled' ||
          prior.requestHash != hash ||
          header.status != 'cancelled') {
        throw StateError(
          'Cancellation request key conflicts with another operation',
        );
      }
      return _result(header);
    }
    if (!header.sealed || header.status != 'draft') {
      throw StateError('Only a completed draft can be cancelled');
    }
    await db
        .into(db.warehouseTransferEvents)
        .insert(
          WarehouseTransferEventsCompanion.insert(
            id: const Uuid().v4(),
            transferId: id,
            kind: 'cancelled',
            requestKey: key,
            requestHash: hash,
            actorId: actor,
            reason: Value(text),
          ),
        );
    final updated =
        await (db.update(
          db.warehouseTransfers,
        )..where((t) => t.id.equals(id) & t.status.equals('draft'))).write(
          const WarehouseTransfersCompanion(status: Value('cancelled')),
        );
    if (updated != 1) {
      throw StateError('Transfer state changed');
    }
    return _result(
      await (db.select(
        db.warehouseTransfers,
      )..where((t) => t.id.equals(id))).getSingle(),
    );
  });
}
