// Mocks generated by Mockito 5.4.6 from annotations
// in tapix/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tapix/features/auth/domain/entities/user_entity.dart' as _i2;
import 'package:tapix/features/auth/domain/repositories/auth_repository_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryInterface extends _i1.Mock
    implements _i3.AuthRepositoryInterface {
  MockAuthRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserEntity?> login(
    String? username,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [username, password],
              {#rememberMe: rememberMe},
            ),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserEntity?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Stream<_i2.UserEntity?> watchCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrentUser, []),
            returnValue: _i4.Stream<_i2.UserEntity?>.empty(),
          )
          as _i4.Stream<_i2.UserEntity?>);

  @override
  _i4.Future<bool> hasAnyUsers() =>
      (super.noSuchMethod(
            Invocation.method(#hasAnyUsers, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.UserEntity> createFirstOwner(
    String? username,
    String? password, {
    String? securityQuestion,
    String? securityAnswer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createFirstOwner,
              [username, password],
              {
                #securityQuestion: securityQuestion,
                #securityAnswer: securityAnswer,
              },
            ),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(
                  #createFirstOwner,
                  [username, password],
                  {
                    #securityQuestion: securityQuestion,
                    #securityAnswer: securityAnswer,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<void> updateLastLogin(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getSecurityQuestion(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getSecurityQuestion, [username]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> resetPasswordWithSecurityAnswer({
    required String? username,
    required String? securityAnswer,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordWithSecurityAnswer, [], {
              #username: username,
              #securityAnswer: securityAnswer,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setSecurityQuestion({
    required int? userId,
    required String? question,
    required String? answer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSecurityQuestion, [], {
              #userId: userId,
              #question: question,
              #answer: answer,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserEntity?> loginWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithBiometrics, []),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);
}
