// Mocks generated by Mockito 5.4.6 from annotations
// in tapix/test/features/accounting/presentation/bloc/accounts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tapix/core/database/app_database.dart' as _i4;
import 'package:tapix/features/accounting/domain/repositories/journal_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i2.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Account>> watchAllAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllAccounts, []),
            returnValue: _i3.Stream<List<_i4.Account>>.empty(),
          )
          as _i3.Stream<List<_i4.Account>>);

  @override
  _i3.Stream<List<_i4.Account>> watchAccountsByType(String? accountType) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountsByType, [accountType]),
            returnValue: _i3.Stream<List<_i4.Account>>.empty(),
          )
          as _i3.Stream<List<_i4.Account>>);

  @override
  _i3.Stream<_i4.Account?> watchAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccount, [id]),
            returnValue: _i3.Stream<_i4.Account?>.empty(),
          )
          as _i3.Stream<_i4.Account?>);

  @override
  _i3.Future<_i4.Account?> getAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, [id]),
            returnValue: _i3.Future<_i4.Account?>.value(),
          )
          as _i3.Future<_i4.Account?>);

  @override
  _i3.Future<_i4.Account?> findAccountByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#findAccountByCode, [code]),
            returnValue: _i3.Future<_i4.Account?>.value(),
          )
          as _i3.Future<_i4.Account?>);

  @override
  _i3.Future<List<_i4.Account>> getChildAccounts(int? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildAccounts, [parentId]),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<int> createAccount({
    required String? accountCode,
    required String? accountName,
    required String? accountType,
    required int? currencyId,
    int? parentAccountId,
    bool? isSystemAccount,
    int? displayOrder,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #accountCode: accountCode,
              #accountName: accountName,
              #accountType: accountType,
              #currencyId: currencyId,
              #parentAccountId: parentAccountId,
              #isSystemAccount: isSystemAccount,
              #displayOrder: displayOrder,
              #description: description,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Stream<int> watchAccountCount({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountCount, [], {#isActive: isActive}),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<List<_i4.JournalEntry>> watchAllJournalEntries() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllJournalEntries, []),
            returnValue: _i3.Stream<List<_i4.JournalEntry>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntry>>);

  @override
  _i3.Stream<List<_i4.JournalEntry>> watchJournalEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByDateRange, [start, end]),
            returnValue: _i3.Stream<List<_i4.JournalEntry>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntry>>);

  @override
  _i3.Stream<List<_i4.JournalEntry>> watchJournalEntriesByType(
    String? entryType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByType, [entryType]),
            returnValue: _i3.Stream<List<_i4.JournalEntry>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntry>>);

  @override
  _i3.Stream<List<_i4.JournalEntry>> watchJournalEntriesByStatus(
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByStatus, [status]),
            returnValue: _i3.Stream<List<_i4.JournalEntry>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntry>>);

  @override
  _i3.Future<_i4.JournalEntry?> getJournalEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntry, [id]),
            returnValue: _i3.Future<_i4.JournalEntry?>.value(),
          )
          as _i3.Future<_i4.JournalEntry?>);

  @override
  _i3.Future<_i4.JournalEntry?> findJournalEntryByNumber(String? entryNumber) =>
      (super.noSuchMethod(
            Invocation.method(#findJournalEntryByNumber, [entryNumber]),
            returnValue: _i3.Future<_i4.JournalEntry?>.value(),
          )
          as _i3.Future<_i4.JournalEntry?>);

  @override
  _i3.Future<_i4.JournalEntry?> findJournalEntryBySource(
    String? sourceTable,
    int? sourceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findJournalEntryBySource, [
              sourceTable,
              sourceId,
            ]),
            returnValue: _i3.Future<_i4.JournalEntry?>.value(),
          )
          as _i3.Future<_i4.JournalEntry?>);

  @override
  _i3.Future<List<_i4.JournalEntry>> searchJournalEntries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchJournalEntries, [query]),
            returnValue: _i3.Future<List<_i4.JournalEntry>>.value(
              <_i4.JournalEntry>[],
            ),
          )
          as _i3.Future<List<_i4.JournalEntry>>);

  @override
  _i3.Future<int> createJournalEntryWithLines({
    required String? description,
    required DateTime? entryDate,
    required String? entryType,
    required List<_i2.JournalLineInput>? lines,
    String? sourceTable,
    int? sourceId,
    int? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createJournalEntryWithLines, [], {
              #description: description,
              #entryDate: entryDate,
              #entryType: entryType,
              #lines: lines,
              #sourceTable: sourceTable,
              #sourceId: sourceId,
              #createdBy: createdBy,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> postJournalEntry(int? entryId, {int? postedBy}) =>
      (super.noSuchMethod(
            Invocation.method(
              #postJournalEntry,
              [entryId],
              {#postedBy: postedBy},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> voidJournalEntry(
    int? entryId, {
    required String? reason,
    int? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #voidJournalEntry,
              [entryId],
              {#reason: reason, #createdBy: createdBy},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Stream<int> watchJournalEntryCount({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntryCount, [], {#status: status}),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<List<_i4.JournalEntryLine>> watchJournalEntryLines(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntryLines, [entryId]),
            returnValue: _i3.Stream<List<_i4.JournalEntryLine>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntryLine>>);

  @override
  _i3.Future<List<_i4.JournalEntryLine>> getJournalEntryLines(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntryLines, [entryId]),
            returnValue: _i3.Future<List<_i4.JournalEntryLine>>.value(
              <_i4.JournalEntryLine>[],
            ),
          )
          as _i3.Future<List<_i4.JournalEntryLine>>);

  @override
  _i3.Stream<List<_i4.JournalEntryLine>> watchJournalLinesByAccount(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalLinesByAccount, [accountId]),
            returnValue: _i3.Stream<List<_i4.JournalEntryLine>>.empty(),
          )
          as _i3.Stream<List<_i4.JournalEntryLine>>);

  @override
  _i3.Stream<List<_i4.AccountingPeriod>> watchAccountingPeriods() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountingPeriods, []),
            returnValue: _i3.Stream<List<_i4.AccountingPeriod>>.empty(),
          )
          as _i3.Stream<List<_i4.AccountingPeriod>>);

  @override
  _i3.Future<_i4.AccountingPeriod?> getActiveAccountingPeriod() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAccountingPeriod, []),
            returnValue: _i3.Future<_i4.AccountingPeriod?>.value(),
          )
          as _i3.Future<_i4.AccountingPeriod?>);

  @override
  _i3.Future<void> seedDefaultAccounts(int? currencyId) =>
      (super.noSuchMethod(
            Invocation.method(#seedDefaultAccounts, [currencyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
