// Mocks generated by Mockito from annotations
// in tapix/test/features/accounting/presentation/bloc/accounts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tapix/core/database/app_database.dart' as _i6;
import 'package:tapix/features/accounting/domain/models/reconciliation_result.dart'
    as _i3;
import 'package:tapix/features/accounting/domain/models/trial_balance.dart'
    as _i2;
import 'package:tapix/features/accounting/domain/repositories/journal_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTrialBalance_0 extends _i1.SmartFake implements _i2.TrialBalance {
  _FakeTrialBalance_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReconciliationResult_1 extends _i1.SmartFake
    implements _i3.ReconciliationResult {
  _FakeReconciliationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JournalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalRepository extends _i1.Mock implements _i4.JournalRepository {
  MockJournalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.Account>> watchAllAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllAccounts, []),
            returnValue: _i5.Stream<List<_i6.Account>>.empty(),
          )
          as _i5.Stream<List<_i6.Account>>);

  @override
  _i5.Stream<List<_i6.Account>> watchAccountsByType(String? accountType) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountsByType, [accountType]),
            returnValue: _i5.Stream<List<_i6.Account>>.empty(),
          )
          as _i5.Stream<List<_i6.Account>>);

  @override
  _i5.Stream<_i6.Account?> watchAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccount, [id]),
            returnValue: _i5.Stream<_i6.Account?>.empty(),
          )
          as _i5.Stream<_i6.Account?>);

  @override
  _i5.Future<_i6.Account?> getAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccount, [id]),
            returnValue: _i5.Future<_i6.Account?>.value(),
          )
          as _i5.Future<_i6.Account?>);

  @override
  _i5.Future<_i6.Account?> findAccountByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#findAccountByCode, [code]),
            returnValue: _i5.Future<_i6.Account?>.value(),
          )
          as _i5.Future<_i6.Account?>);

  @override
  _i5.Future<List<_i6.Account>> getChildAccounts(int? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildAccounts, [parentId]),
            returnValue: _i5.Future<List<_i6.Account>>.value(<_i6.Account>[]),
          )
          as _i5.Future<List<_i6.Account>>);

  @override
  _i5.Future<int> createAccount({
    required String? accountCode,
    required String? accountName,
    required String? accountType,
    required int? currencyId,
    int? parentAccountId,
    bool? isSystemAccount,
    int? displayOrder,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #accountCode: accountCode,
              #accountName: accountName,
              #accountType: accountType,
              #currencyId: currencyId,
              #parentAccountId: parentAccountId,
              #isSystemAccount: isSystemAccount,
              #displayOrder: displayOrder,
              #description: description,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateAccount(_i6.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<int> watchAccountCount({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountCount, [], {#isActive: isActive}),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Stream<List<_i6.JournalEntry>> watchAllJournalEntries() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllJournalEntries, []),
            returnValue: _i5.Stream<List<_i6.JournalEntry>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntry>>);

  @override
  _i5.Stream<List<_i6.JournalEntry>> watchJournalEntriesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByDateRange, [start, end]),
            returnValue: _i5.Stream<List<_i6.JournalEntry>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntry>>);

  @override
  _i5.Stream<List<_i6.JournalEntry>> watchJournalEntriesByType(
    String? entryType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByType, [entryType]),
            returnValue: _i5.Stream<List<_i6.JournalEntry>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntry>>);

  @override
  _i5.Stream<List<_i6.JournalEntry>> watchJournalEntriesByStatus(
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntriesByStatus, [status]),
            returnValue: _i5.Stream<List<_i6.JournalEntry>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntry>>);

  @override
  _i5.Future<_i6.JournalEntry?> getJournalEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntry, [id]),
            returnValue: _i5.Future<_i6.JournalEntry?>.value(),
          )
          as _i5.Future<_i6.JournalEntry?>);

  @override
  _i5.Future<_i6.JournalEntry?> findJournalEntryByNumber(String? entryNumber) =>
      (super.noSuchMethod(
            Invocation.method(#findJournalEntryByNumber, [entryNumber]),
            returnValue: _i5.Future<_i6.JournalEntry?>.value(),
          )
          as _i5.Future<_i6.JournalEntry?>);

  @override
  _i5.Future<_i6.JournalEntry?> findJournalEntryBySource(
    String? sourceTable,
    int? sourceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findJournalEntryBySource, [
              sourceTable,
              sourceId,
            ]),
            returnValue: _i5.Future<_i6.JournalEntry?>.value(),
          )
          as _i5.Future<_i6.JournalEntry?>);

  @override
  _i5.Future<List<_i6.JournalEntry>> searchJournalEntries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchJournalEntries, [query]),
            returnValue: _i5.Future<List<_i6.JournalEntry>>.value(
              <_i6.JournalEntry>[],
            ),
          )
          as _i5.Future<List<_i6.JournalEntry>>);

  @override
  _i5.Future<int> createJournalEntryWithLines({
    required String? description,
    required DateTime? entryDate,
    required String? entryType,
    required List<_i4.JournalLineInput>? lines,
    String? sourceTable,
    int? sourceId,
    int? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createJournalEntryWithLines, [], {
              #description: description,
              #entryDate: entryDate,
              #entryType: entryType,
              #lines: lines,
              #sourceTable: sourceTable,
              #sourceId: sourceId,
              #createdBy: createdBy,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> postJournalEntry(int? entryId, {int? postedBy}) =>
      (super.noSuchMethod(
            Invocation.method(
              #postJournalEntry,
              [entryId],
              {#postedBy: postedBy},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> voidJournalEntry(
    int? entryId, {
    required String? reason,
    int? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #voidJournalEntry,
              [entryId],
              {#reason: reason, #createdBy: createdBy},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<int> watchJournalEntryCount({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntryCount, [], {#status: status}),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Stream<List<_i6.JournalEntryLine>> watchJournalEntryLines(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalEntryLines, [entryId]),
            returnValue: _i5.Stream<List<_i6.JournalEntryLine>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntryLine>>);

  @override
  _i5.Future<List<_i6.JournalEntryLine>> getJournalEntryLines(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntryLines, [entryId]),
            returnValue: _i5.Future<List<_i6.JournalEntryLine>>.value(
              <_i6.JournalEntryLine>[],
            ),
          )
          as _i5.Future<List<_i6.JournalEntryLine>>);

  @override
  _i5.Stream<List<_i6.JournalEntryLine>> watchJournalLinesByAccount(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchJournalLinesByAccount, [accountId]),
            returnValue: _i5.Stream<List<_i6.JournalEntryLine>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntryLine>>);

  @override
  _i5.Stream<List<_i6.AccountingPeriod>> watchAccountingPeriods() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountingPeriods, []),
            returnValue: _i5.Stream<List<_i6.AccountingPeriod>>.empty(),
          )
          as _i5.Stream<List<_i6.AccountingPeriod>>);

  @override
  _i5.Future<_i6.AccountingPeriod?> getActiveAccountingPeriod() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAccountingPeriod, []),
            returnValue: _i5.Future<_i6.AccountingPeriod?>.value(),
          )
          as _i5.Future<_i6.AccountingPeriod?>);

  @override
  _i5.Future<void> seedDefaultAccounts(int? currencyId) =>
      (super.noSuchMethod(
            Invocation.method(#seedDefaultAccounts, [currencyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.TrialBalance> getTrialBalance({DateTime? asOfDate}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrialBalance, [], {#asOfDate: asOfDate}),
            returnValue: _i5.Future<_i2.TrialBalance>.value(
              _FakeTrialBalance_0(
                this,
                Invocation.method(#getTrialBalance, [], {#asOfDate: asOfDate}),
              ),
            ),
          )
          as _i5.Future<_i2.TrialBalance>);

  @override
  _i5.Future<_i3.ReconciliationResult> reconcileBalances() =>
      (super.noSuchMethod(
            Invocation.method(#reconcileBalances, []),
            returnValue: _i5.Future<_i3.ReconciliationResult>.value(
              _FakeReconciliationResult_1(
                this,
                Invocation.method(#reconcileBalances, []),
              ),
            ),
          )
          as _i5.Future<_i3.ReconciliationResult>);

  @override
  _i5.Stream<List<_i6.JournalEntryLine>> watchPostedLinesByDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchPostedLinesByDateRange, [
              startDate,
              endDate,
            ]),
            returnValue: _i5.Stream<List<_i6.JournalEntryLine>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntryLine>>);

  @override
  _i5.Stream<List<_i6.JournalEntryLine>> watchPostedLinesByAccountAndDateRange(
    int? accountId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchPostedLinesByAccountAndDateRange, [
              accountId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Stream<List<_i6.JournalEntryLine>>.empty(),
          )
          as _i5.Stream<List<_i6.JournalEntryLine>>);
}
