import 'package:decimal/decimal.dart';
import '../entities/product_entity.dart';
import '../entities/price_history_entity.dart';
import '../repositories/product_repository.dart';

class BulkUpdatePrices {
  final ProductRepository _repository;

  BulkUpdatePrices(this._repository);

  Future<void> call({
    required List<Product> products,
    required Map<int, Map<String, Decimal>> priceChanges,
    required int userId,
    String? changeReason,
  }) async {
    if (priceChanges.isEmpty) return;

    // Create price history records before updating
    final historyRecords = <PriceHistory>[];

    for (final entry in priceChanges.entries) {
      final productId = entry.key;
      final changes = entry.value;

      final product = products.firstWhere(
        (p) => p.id == productId,
        orElse: () => throw Exception('Product $productId not found'),
      );

      final history = PriceHistory(
        id: 0, // Will be generated by database
        productId: productId,
        oldCostCents: product.costCents.toDouble().round(),
        newCostCents: changes.containsKey('costCents')
            ? changes['costCents']!.toDouble().round()
            : product.costCents.toDouble().round(),
        oldPriceCents: product.priceCents.toDouble().round(),
        newPriceCents: changes.containsKey('priceCents')
            ? changes['priceCents']!.toDouble().round()
            : product.priceCents.toDouble().round(),
        oldWholesalePriceCents: product.wholesalePriceCents?.toDouble().round(),
        newWholesalePriceCents: changes.containsKey('wholesalePriceCents')
            ? changes['wholesalePriceCents']!.toDouble().round()
            : product.wholesalePriceCents?.toDouble().round(),
        userId: userId,
        changeReason: changeReason,
        createdAt: DateTime.now(),
      );

      historyRecords.add(history);
    }

    // Perform transaction: update products and create history records
    await _repository.bulkUpdatePricesWithHistory(
      products: products,
      priceChanges: priceChanges,
      historyRecords: historyRecords,
    );
  }
}
