import '../entities/price_history_entity.dart';
import '../repositories/product_repository.dart';

class TrackPriceHistory {
  final ProductRepository _repository;

  TrackPriceHistory(this._repository);

  Future<List<PriceHistory>> call(int productId) async {
    return await _repository.getPriceHistory(productId);
  }

  Future<void> recordPriceChange({
    required int productId,
    required int oldPriceCents,
    required int newPriceCents,
    required int userId,
    String? changeReason,
  }) async {
    final history = PriceHistory(
      id: 0, // Will be generated by database
      productId: productId,
      oldPriceCents: oldPriceCents,
      newPriceCents: newPriceCents,
      oldCostCents: 0, // Not tracking cost changes in this use case
      newCostCents: 0,
      userId: userId,
      changeReason: changeReason,
      createdAt: DateTime.now(),
    );

    await _repository.createPriceHistory(history);
  }
}
