// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqavyu3GG1_N6x4lDCYelVNcB8q0XB_w',
    appId: '1:970698687113:web:4fc1ecb56ff24274167c58',
    messagingSenderId: '970698687113',
    projectId: 'tapix-1d5fa',
    authDomain: 'tapix-1d5fa.firebaseapp.com',
    storageBucket: 'tapix-1d5fa.firebasestorage.app',
    measurementId: 'G-5TN1NVX00D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLo84R-IgUV5I1wzqR-jqOHYbt-v1h62Q',
    appId: '1:970698687113:android:f615ada00ed2c6d0167c58',
    messagingSenderId: '970698687113',
    projectId: 'tapix-1d5fa',
    storageBucket: 'tapix-1d5fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBAIfcPlq2L4j5-u-NaIwJMaqfI-l-mnE',
    appId: '1:970698687113:ios:cef718cc526aadc0167c58',
    messagingSenderId: '970698687113',
    projectId: 'tapix-1d5fa',
    storageBucket: 'tapix-1d5fa.firebasestorage.app',
    iosBundleId: 'com.tapix.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBAIfcPlq2L4j5-u-NaIwJMaqfI-l-mnE',
    appId: '1:970698687113:ios:295ed8145325e66c167c58',
    messagingSenderId: '970698687113',
    projectId: 'tapix-1d5fa',
    storageBucket: 'tapix-1d5fa.firebasestorage.app',
    iosBundleId: 'com.tapix.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaqavyu3GG1_N6x4lDCYelVNcB8q0XB_w',
    appId: '1:970698687113:web:93e5f8bdfecdc47a167c58',
    messagingSenderId: '970698687113',
    projectId: 'tapix-1d5fa',
    authDomain: 'tapix-1d5fa.firebaseapp.com',
    storageBucket: 'tapix-1d5fa.firebasestorage.app',
    measurementId: 'G-T19VR527RS',
  );
}
