// Mocks generated by Mockito 5.4.6 from annotations
// in tapix/test/features/products/presentation/bloc/edit_prices_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:decimal/decimal.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tapix/features/products/domain/entities/price_history_entity.dart'
    as _i6;
import 'package:tapix/features/products/domain/entities/product_entity.dart'
    as _i4;
import 'package:tapix/features/products/domain/repositories/product_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Product>> watchAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllProducts, []),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<_i4.Product?> watchProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchProduct, [id]),
            returnValue: _i3.Stream<_i4.Product?>.empty(),
          )
          as _i3.Stream<_i4.Product?>);

  @override
  _i3.Future<List<_i4.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<_i4.Product?> findBySku(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#findBySku, [sku]),
            returnValue: _i3.Future<_i4.Product?>.value(),
          )
          as _i3.Future<_i4.Product?>);

  @override
  _i3.Future<_i4.Product?> findByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#findByBarcode, [barcode]),
            returnValue: _i3.Future<_i4.Product?>.value(),
          )
          as _i3.Future<_i4.Product?>);

  @override
  _i3.Future<List<_i4.Product>> filterProducts({
    int? categoryId,
    String? stockStatus,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterProducts, [], {
              #categoryId: categoryId,
              #stockStatus: stockStatus,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Stream<List<_i4.Product>> watchFilteredProducts({
    int? categoryId,
    String? stockStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchFilteredProducts, [], {
              #categoryId: categoryId,
              #stockStatus: stockStatus,
            }),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Stream<List<_i4.Product>> watchProductsForExport({
    int? categoryId,
    int? supplierId,
    bool? activeOnly = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchProductsForExport, [], {
              #categoryId: categoryId,
              #supplierId: supplierId,
              #activeOnly: activeOnly,
            }),
            returnValue: _i3.Stream<List<_i4.Product>>.empty(),
          )
          as _i3.Stream<List<_i4.Product>>);

  @override
  _i3.Future<List<_i4.Product>> fetchProductsForExport({
    int? categoryId,
    int? supplierId,
    bool? activeOnly = true,
    int? limit = 1000,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsForExport, [], {
              #categoryId: categoryId,
              #supplierId: supplierId,
              #activeOnly: activeOnly,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.Product>>.value(<_i4.Product>[]),
          )
          as _i3.Future<List<_i4.Product>>);

  @override
  _i3.Future<int> createProduct({
    required String? name,
    String? nameAr,
    String? nameFr,
    String? description,
    String? sku,
    String? barcode,
    required _i5.Decimal? costCents,
    required _i5.Decimal? priceCents,
    _i5.Decimal? wholesalePriceCents,
    required int? stockQuantity,
    required int? minQuantity,
    int? categoryId,
    int? supplierId,
    int? currencyId,
    String? imagePath,
    bool? hasVariants = false,
    bool? isTaxable = false,
    int? taxRateBps = 0,
    bool? isActive = true,
    bool? trackInventory = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [], {
              #name: name,
              #nameAr: nameAr,
              #nameFr: nameFr,
              #description: description,
              #sku: sku,
              #barcode: barcode,
              #costCents: costCents,
              #priceCents: priceCents,
              #wholesalePriceCents: wholesalePriceCents,
              #stockQuantity: stockQuantity,
              #minQuantity: minQuantity,
              #categoryId: categoryId,
              #supplierId: supplierId,
              #currencyId: currencyId,
              #imagePath: imagePath,
              #hasVariants: hasVariants,
              #isTaxable: isTaxable,
              #taxRateBps: taxRateBps,
              #isActive: isActive,
              #trackInventory: trackInventory,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateProduct(_i4.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> bulkDeleteProducts(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteProducts, [ids]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deactivateProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateProduct, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> bulkDeactivateProducts(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeactivateProducts, [ids]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<int>> findProductIdsReferencedByOpenPurchases(
    List<int>? productIds, {
    Set<String>? closedPurchaseStatuses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #findProductIdsReferencedByOpenPurchases,
              [productIds],
              {#closedPurchaseStatuses: closedPurchaseStatuses},
            ),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<Map<int, int>> bulkCreateProducts(
    List<_i2.BulkProductData>? products,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkCreateProducts, [products]),
            returnValue: _i3.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i3.Future<Map<int, int>>);

  @override
  _i3.Future<void> bulkUpdatePricesWithHistory({
    required List<_i4.Product>? products,
    required Map<int, Map<String, _i5.Decimal>>? priceChanges,
    required List<_i6.PriceHistory>? historyRecords,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdatePricesWithHistory, [], {
              #products: products,
              #priceChanges: priceChanges,
              #historyRecords: historyRecords,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.PriceHistory>> getPriceHistory(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getPriceHistory, [productId]),
            returnValue: _i3.Future<List<_i6.PriceHistory>>.value(
              <_i6.PriceHistory>[],
            ),
          )
          as _i3.Future<List<_i6.PriceHistory>>);

  @override
  _i3.Future<void> createPriceHistory(_i6.PriceHistory? history) =>
      (super.noSuchMethod(
            Invocation.method(#createPriceHistory, [history]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
