// Mocks generated by Mockito 5.4.6 from annotations
// in tapix/test/features/barcode/presentation/bloc/barcode_design_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i12;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:pdf/widgets.dart' as _i8;
import 'package:tapix/core/database/app_database.dart' as _i2;
import 'package:tapix/core/database/daos/barcode_template_dao.dart' as _i5;
import 'package:tapix/features/barcode/domain/models/barcode_design_state.dart'
    as _i13;
import 'package:tapix/features/barcode/services/barcode_printer_service.dart'
    as _i7;
import 'package:tapix/features/products/domain/entities/product_entity.dart'
    as _i11;
import 'package:tapix/features/settings/data/services/company_profile_service.dart'
    as _i14;
import 'package:tapix/features/settings/domain/entities/company_profile.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BarcodeTemplatesTable_6 extends _i1.SmartFake
    implements _i2.$BarcodeTemplatesTable {
  _Fake$BarcodeTemplatesTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProductCategoriesTable_7 extends _i1.SmartFake
    implements _i2.$ProductCategoriesTable {
  _Fake$ProductCategoriesTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CurrenciesTable_8 extends _i1.SmartFake
    implements _i2.$CurrenciesTable {
  _Fake$CurrenciesTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SuppliersTable_9 extends _i1.SmartFake
    implements _i2.$SuppliersTable {
  _Fake$SuppliersTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProductsTable_10 extends _i1.SmartFake
    implements _i2.$ProductsTable {
  _Fake$ProductsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProductColorsTable_11 extends _i1.SmartFake
    implements _i2.$ProductColorsTable {
  _Fake$ProductColorsTable_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SizesTable_12 extends _i1.SmartFake implements _i2.$SizesTable {
  _Fake$SizesTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ProductVariantsTable_13 extends _i1.SmartFake
    implements _i2.$ProductVariantsTable {
  _Fake$ProductVariantsTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PrintHistoriesTable_14 extends _i1.SmartFake
    implements _i2.$PrintHistoriesTable {
  _Fake$PrintHistoriesTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBarcodeTemplateDaoManager_15 extends _i1.SmartFake
    implements _i5.BarcodeTemplateDaoManager {
  _FakeBarcodeTemplateDaoManager_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_16<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_17<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_18<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_19<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_20<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_21<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_22<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_23<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_24 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePrinterConfig_25 extends _i1.SmartFake implements _i7.PrinterConfig {
  _FakePrinterConfig_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBarcode_26 extends _i1.SmartFake implements _i8.Barcode {
  _FakeBarcode_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompanyProfile_27 extends _i1.SmartFake
    implements _i9.CompanyProfile {
  _FakeCompanyProfile_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BarcodeTemplateDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodeTemplateDao extends _i1.Mock
    implements _i5.BarcodeTemplateDao {
  MockBarcodeTemplateDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i10.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$BarcodeTemplatesTable get barcodeTemplates =>
      (super.noSuchMethod(
            Invocation.getter(#barcodeTemplates),
            returnValue: _Fake$BarcodeTemplatesTable_6(
              this,
              Invocation.getter(#barcodeTemplates),
            ),
          )
          as _i2.$BarcodeTemplatesTable);

  @override
  _i2.$ProductCategoriesTable get productCategories =>
      (super.noSuchMethod(
            Invocation.getter(#productCategories),
            returnValue: _Fake$ProductCategoriesTable_7(
              this,
              Invocation.getter(#productCategories),
            ),
          )
          as _i2.$ProductCategoriesTable);

  @override
  _i2.$CurrenciesTable get currencies =>
      (super.noSuchMethod(
            Invocation.getter(#currencies),
            returnValue: _Fake$CurrenciesTable_8(
              this,
              Invocation.getter(#currencies),
            ),
          )
          as _i2.$CurrenciesTable);

  @override
  _i2.$SuppliersTable get suppliers =>
      (super.noSuchMethod(
            Invocation.getter(#suppliers),
            returnValue: _Fake$SuppliersTable_9(
              this,
              Invocation.getter(#suppliers),
            ),
          )
          as _i2.$SuppliersTable);

  @override
  _i2.$ProductsTable get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _Fake$ProductsTable_10(
              this,
              Invocation.getter(#products),
            ),
          )
          as _i2.$ProductsTable);

  @override
  _i2.$ProductColorsTable get productColors =>
      (super.noSuchMethod(
            Invocation.getter(#productColors),
            returnValue: _Fake$ProductColorsTable_11(
              this,
              Invocation.getter(#productColors),
            ),
          )
          as _i2.$ProductColorsTable);

  @override
  _i2.$SizesTable get sizes =>
      (super.noSuchMethod(
            Invocation.getter(#sizes),
            returnValue: _Fake$SizesTable_12(this, Invocation.getter(#sizes)),
          )
          as _i2.$SizesTable);

  @override
  _i2.$ProductVariantsTable get productVariants =>
      (super.noSuchMethod(
            Invocation.getter(#productVariants),
            returnValue: _Fake$ProductVariantsTable_13(
              this,
              Invocation.getter(#productVariants),
            ),
          )
          as _i2.$ProductVariantsTable);

  @override
  _i2.$PrintHistoriesTable get printHistories =>
      (super.noSuchMethod(
            Invocation.getter(#printHistories),
            returnValue: _Fake$PrintHistoriesTable_14(
              this,
              Invocation.getter(#printHistories),
            ),
          )
          as _i2.$PrintHistoriesTable);

  @override
  _i5.BarcodeTemplateDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeBarcodeTemplateDaoManager_15(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.BarcodeTemplateDaoManager);

  @override
  _i6.Stream<List<_i2.BarcodeTemplate>> watchTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#watchTemplates, []),
            returnValue: _i6.Stream<List<_i2.BarcodeTemplate>>.empty(),
          )
          as _i6.Stream<List<_i2.BarcodeTemplate>>);

  @override
  _i6.Future<List<_i2.BarcodeTemplate>> getTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#getTemplates, []),
            returnValue: _i6.Future<List<_i2.BarcodeTemplate>>.value(
              <_i2.BarcodeTemplate>[],
            ),
          )
          as _i6.Future<List<_i2.BarcodeTemplate>>);

  @override
  _i6.Future<_i2.BarcodeTemplate?> getTemplateById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTemplateById, [id]),
            returnValue: _i6.Future<_i2.BarcodeTemplate?>.value(),
          )
          as _i6.Future<_i2.BarcodeTemplate?>);

  @override
  _i6.Future<_i2.BarcodeTemplate?> getDefaultTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultTemplate, []),
            returnValue: _i6.Future<_i2.BarcodeTemplate?>.value(),
          )
          as _i6.Future<_i2.BarcodeTemplate?>);

  @override
  _i6.Stream<_i2.BarcodeTemplate?> watchDefaultTemplate() =>
      (super.noSuchMethod(
            Invocation.method(#watchDefaultTemplate, []),
            returnValue: _i6.Stream<_i2.BarcodeTemplate?>.empty(),
          )
          as _i6.Stream<_i2.BarcodeTemplate?>);

  @override
  _i6.Future<int> createTemplate(_i2.BarcodeTemplatesCompanion? template) =>
      (super.noSuchMethod(
            Invocation.method(#createTemplate, [template]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<bool> updateTemplate(_i2.BarcodeTemplate? template) =>
      (super.noSuchMethod(
            Invocation.method(#updateTemplate, [template]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> setDefaultTemplate(int? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultTemplate, [templateId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> deleteTemplate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTemplate, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> logPrint({
    required int? productId,
    int? variantId,
    int? templateId,
    required int? quantityPrinted,
    String? printerName,
    String? printType = 'single',
    String? status = 'success',
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPrint, [], {
              #productId: productId,
              #variantId: variantId,
              #templateId: templateId,
              #quantityPrinted: quantityPrinted,
              #printerName: printerName,
              #printType: printType,
              #status: status,
              #errorMessage: errorMessage,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Stream<List<_i2.PrintHistory>> watchPrintHistoryForProduct(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchPrintHistoryForProduct, [productId]),
            returnValue: _i6.Stream<List<_i2.PrintHistory>>.empty(),
          )
          as _i6.Stream<List<_i2.PrintHistory>>);

  @override
  _i6.Future<List<_i2.PrintHistory>> getPrintHistory({
    int? productId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPrintHistory, [], {
              #productId: productId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i2.PrintHistory>>.value(
              <_i2.PrintHistory>[],
            ),
          )
          as _i6.Future<List<_i2.PrintHistory>>);

  @override
  _i6.Future<int> getTotalPrintsForProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPrintsForProduct, [productId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i10.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_17<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_18<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_19<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_20<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_21<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_22<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_23<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_23<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_16<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeUpdateInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_24(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [BarcodePrinterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarcodePrinterService extends _i1.Mock
    implements _i7.BarcodePrinterService {
  MockBarcodePrinterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBluetoothPrintingSupported =>
      (super.noSuchMethod(
            Invocation.getter(#isBluetoothPrintingSupported),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<List<_i7.BluetoothPrinterDevice>> getBondedBluetoothPrinters() =>
      (super.noSuchMethod(
            Invocation.method(#getBondedBluetoothPrinters, []),
            returnValue: _i6.Future<List<_i7.BluetoothPrinterDevice>>.value(
              <_i7.BluetoothPrinterDevice>[],
            ),
          )
          as _i6.Future<List<_i7.BluetoothPrinterDevice>>);

  @override
  _i6.Future<void> saveSettings({
    double? widthMm,
    double? heightMm,
    bool? includeName,
    bool? includePrice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [], {
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.PrinterConfig> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i6.Future<_i7.PrinterConfig>.value(
              _FakePrinterConfig_25(this, Invocation.method(#getSettings, [])),
            ),
          )
          as _i6.Future<_i7.PrinterConfig>);

  @override
  _i6.Future<void> printThermalLabel({
    required _i11.Product? product,
    required _i8.Barcode? barcode,
    double? widthMm = 58.0,
    double? heightMm = 40.0,
    bool? includeName = true,
    bool? includePrice = true,
    bool? includeBarcode = true,
    bool? includeCompanyName = false,
    String? companyName,
    bool? includeCompanyContact = false,
    String? companyAddress,
    String? companyPhone,
    int? copies = 1,
    String? variantInfo,
    bool? includeVariantInfo = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printThermalLabel, [], {
              #product: product,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #includeBarcode: includeBarcode,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #copies: copies,
              #variantInfo: variantInfo,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> printA4Grid({
    required _i11.Product? product,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    required bool? includeBarcode,
    required bool? includeCompanyName,
    required String? companyName,
    required bool? includeCompanyContact,
    required String? companyAddress,
    required String? companyPhone,
    required int? copies,
    required int? labelsPerRow,
    required double? horizontalGapMm,
    required double? verticalGapMm,
    required double? pageMarginMm,
    required String? variantInfo,
    required bool? includeVariantInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printA4Grid, [], {
              #product: product,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #includeBarcode: includeBarcode,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #copies: copies,
              #labelsPerRow: labelsPerRow,
              #horizontalGapMm: horizontalGapMm,
              #verticalGapMm: verticalGapMm,
              #pageMarginMm: pageMarginMm,
              #variantInfo: variantInfo,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> printLabel({
    required _i11.Product? product,
    required _i8.Barcode? barcode,
    double? widthMm = 58.0,
    double? heightMm = 40.0,
    bool? includeName = true,
    bool? includePrice = true,
    bool? includeBarcode = true,
    bool? includeCompanyName = false,
    String? companyName,
    bool? includeCompanyContact = false,
    String? companyAddress,
    String? companyPhone,
    int? copies = 1,
    bool? isA4Mode = false,
    int? labelsPerRow = 3,
    double? horizontalGapMm = 2.0,
    double? verticalGapMm = 2.0,
    double? pageMarginMm = 10.0,
    String? variantInfo,
    bool? includeVariantInfo = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printLabel, [], {
              #product: product,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #includeBarcode: includeBarcode,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #copies: copies,
              #isA4Mode: isA4Mode,
              #labelsPerRow: labelsPerRow,
              #horizontalGapMm: horizontalGapMm,
              #verticalGapMm: verticalGapMm,
              #pageMarginMm: pageMarginMm,
              #variantInfo: variantInfo,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i12.Uint8List> generatePdfLabel({
    required _i11.Product? product,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    bool? includeBarcode = true,
    bool? includeCompanyName,
    String? companyName,
    bool? includeCompanyContact,
    String? companyAddress,
    String? companyPhone,
    int? copies,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePdfLabel, [], {
              #product: product,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #includeBarcode: includeBarcode,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #copies: copies,
            }),
            returnValue: _i6.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
          )
          as _i6.Future<_i12.Uint8List>);

  @override
  _i6.Future<void> shareLabelPdf({
    required _i11.Product? product,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    bool? includeBarcode = true,
    bool? includeCompanyName,
    String? companyName,
    bool? includeCompanyContact,
    String? companyAddress,
    String? companyPhone,
    int? copies,
    bool? isA4Mode,
    int? labelsPerRow,
    double? horizontalGapMm,
    double? verticalGapMm,
    double? pageMarginMm,
    String? variantInfo,
    bool? includeVariantInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareLabelPdf, [], {
              #product: product,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #includeBarcode: includeBarcode,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #copies: copies,
              #isA4Mode: isA4Mode,
              #labelsPerRow: labelsPerRow,
              #horizontalGapMm: horizontalGapMm,
              #verticalGapMm: verticalGapMm,
              #pageMarginMm: pageMarginMm,
              #variantInfo: variantInfo,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> shareLabelsPdfBatch({
    required List<({int copies, _i11.Product product, String? variantInfo})>?
    jobs,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    required _i13.PriceDisplayMode? priceDisplayMode,
    required bool? includeBarcode,
    required bool? includeSku,
    required bool? includeCompanyName,
    required String? companyName,
    required bool? includeCompanyContact,
    required String? companyAddress,
    required String? companyPhone,
    required bool? isA4Mode,
    required int? labelsPerRow,
    required double? horizontalGapMm,
    required double? verticalGapMm,
    required double? pageMarginMm,
    required bool? includeVariantInfo,
    String? filename = 'Labels.pdf',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareLabelsPdfBatch, [], {
              #jobs: jobs,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #priceDisplayMode: priceDisplayMode,
              #includeBarcode: includeBarcode,
              #includeSku: includeSku,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #isA4Mode: isA4Mode,
              #labelsPerRow: labelsPerRow,
              #horizontalGapMm: horizontalGapMm,
              #verticalGapMm: verticalGapMm,
              #pageMarginMm: pageMarginMm,
              #includeVariantInfo: includeVariantInfo,
              #filename: filename,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> printLabelsPdfBatch({
    required List<({int copies, _i11.Product product, String? variantInfo})>?
    jobs,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    required _i13.PriceDisplayMode? priceDisplayMode,
    required bool? includeBarcode,
    required bool? includeSku,
    required bool? includeCompanyName,
    required String? companyName,
    required bool? includeCompanyContact,
    required String? companyAddress,
    required String? companyPhone,
    required bool? isA4Mode,
    required int? labelsPerRow,
    required double? horizontalGapMm,
    required double? verticalGapMm,
    required double? pageMarginMm,
    required bool? includeVariantInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printLabelsPdfBatch, [], {
              #jobs: jobs,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #priceDisplayMode: priceDisplayMode,
              #includeBarcode: includeBarcode,
              #includeSku: includeSku,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #isA4Mode: isA4Mode,
              #labelsPerRow: labelsPerRow,
              #horizontalGapMm: horizontalGapMm,
              #verticalGapMm: verticalGapMm,
              #pageMarginMm: pageMarginMm,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> printLabelsBluetoothBatch({
    required String? bluetoothAddress,
    required List<({int copies, _i11.Product product, String? variantInfo})>?
    jobs,
    required _i8.Barcode? barcode,
    required double? widthMm,
    required double? heightMm,
    required bool? includeName,
    required bool? includePrice,
    required _i13.PriceDisplayMode? priceDisplayMode,
    required bool? includeBarcode,
    required bool? includeSku,
    required bool? includeCompanyName,
    required String? companyName,
    required bool? includeCompanyContact,
    required String? companyAddress,
    required String? companyPhone,
    required bool? includeVariantInfo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#printLabelsBluetoothBatch, [], {
              #bluetoothAddress: bluetoothAddress,
              #jobs: jobs,
              #barcode: barcode,
              #widthMm: widthMm,
              #heightMm: heightMm,
              #includeName: includeName,
              #includePrice: includePrice,
              #priceDisplayMode: priceDisplayMode,
              #includeBarcode: includeBarcode,
              #includeSku: includeSku,
              #includeCompanyName: includeCompanyName,
              #companyName: companyName,
              #includeCompanyContact: includeCompanyContact,
              #companyAddress: companyAddress,
              #companyPhone: companyPhone,
              #includeVariantInfo: includeVariantInfo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i8.Barcode getBarcodeTypeFromString(String? typeString) =>
      (super.noSuchMethod(
            Invocation.method(#getBarcodeTypeFromString, [typeString]),
            returnValue: _FakeBarcode_26(
              this,
              Invocation.method(#getBarcodeTypeFromString, [typeString]),
            ),
          )
          as _i8.Barcode);

  @override
  _i8.Barcode getBarcodeTypeAuto(String? data, String? typeString) =>
      (super.noSuchMethod(
            Invocation.method(#getBarcodeTypeAuto, [data, typeString]),
            returnValue: _FakeBarcode_26(
              this,
              Invocation.method(#getBarcodeTypeAuto, [data, typeString]),
            ),
          )
          as _i8.Barcode);
}

/// A class which mocks [CompanyProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyProfileService extends _i1.Mock
    implements _i14.CompanyProfileService {
  MockCompanyProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i9.CompanyProfile> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i6.Stream<_i9.CompanyProfile>.empty(),
          )
          as _i6.Stream<_i9.CompanyProfile>);

  @override
  _i6.Future<_i9.CompanyProfile> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i9.CompanyProfile>.value(
              _FakeCompanyProfile_27(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i6.Future<_i9.CompanyProfile>);

  @override
  _i6.Stream<_i9.CompanyProfile> watchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, []),
            returnValue: _i6.Stream<_i9.CompanyProfile>.empty(),
          )
          as _i6.Stream<_i9.CompanyProfile>);

  @override
  _i6.Future<void> saveProfile(_i9.CompanyProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
